##                                                                                                              
## Dit bestand is in toml-formaat, zie: https://github.com/mojombo/toml                                         
##                                                                                                              

logfile = "log/alpiner.log"

about = '''
Experimentele server, niet voor productiedoeleinden.

Info: https://github.com/rug-compling/alpino-api
'''

port = 11200

tmp = "/dev/shm/alpiner"

# werkelijke interval een minuut langer dan de interval gerapporteerd aan gebruiker
interval = 300
interval_system = 360

workers = 1

timeout_default = 60

timeout_max = 600

timeout_values = [ 60 ]

max_jobs = 1

max_tokens = 100

[[alpino]]
server = "127.0.0.1:11211"
timeout = 60
